### ISSUE TITLE
1y4m: fails to generate some assemby mmcif files with NPE

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#155]
Stack trace:
```
Exception in thread "main" java.lang.NullPointerException
        at eppic.assembly.Assembly.centerSymmetrically(Assembly.java:474)
        at eppic.assembly.Assembly.getStructurePacked(Assembly.java:419)
        at eppic.assembly.Assembly.writeToMmCifFile(Assembly.java:868)
        at eppic.Main.doWriteCoordFiles(Main.java:532)
        at eppic.Main.run(Main.java:942)
        at eppic.Main.run(Main.java:879)
        at eppic.Main.main(Main.java:853)

```

**Comment by josemduarte** [comment]
This looks similar to #156, some problem with quaternary symmetry code

**Comment by josemduarte** [comment]
Same problem in 2n8r
