### ISSUE TITLE
Some entries crash with IllegalStateException

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#167]
Examples: 2kmj, 1dzi. The stack trace:

```
Exception in thread "main" java.lang.IllegalStateException: MomentsOfInertia: no points defined
        at org.biojava.nbio.structure.symmetry.geometry.MomentsOfInertia.centerOfMass(MomentsOfInertia.java:59)
        at org.biojava.nbio.structure.symmetry.geometry.MomentsOfInertia.getInertiaTensor(MomentsOfInertia.java:177)
        at org.biojava.nbio.structure.symmetry.geometry.MomentsOfInertia.diagonalizeTensor(MomentsOfInertia.java:200)
        at org.biojava.nbio.structure.symmetry.geometry.MomentsOfInertia.getPrincipalAxes(MomentsOfInertia.java:84)
        at org.biojava.nbio.structure.symmetry.core.RotationAxisAligner.calcPrincipalAxes(RotationAxisAligner.java:481)
        at org.biojava.nbio.structure.symmetry.core.RotationAxisAligner.run(RotationAxisAligner.java:204)
        at org.biojava.nbio.structure.symmetry.core.RotationAxisAligner.getGeometricCenter(RotationAxisAligner.java:160)
        at eppic.assembly.Assembly.centerSymmetrically(Assembly.java:544)
        at eppic.assembly.Assembly.getStructurePacked(Assembly.java:422)
        at eppic.assembly.Assembly.writeToMmCifFile(Assembly.java:895)
        at eppic.Main.doWriteCoordFiles(Main.java:534)
        at eppic.Main.run(Main.java:976)
        at eppic.Main.run(Main.java:913)
        at eppic.Main.main(Main.java:887)

```

**Comment by josemduarte** [comment]
Both cases are due to chains that have no representative atoms at all (no CA or no phosphate group for nucleic acid). 1dzi looks like a problem in parsing in biojava, a chain is composed of a CO ion and HOH only.

**Comment by josemduarte** [comment]
BTW the exception should be IllegalArgument, I'll patch biojava for that at least. 

The rest of the problems need more time to fix, I suspect it's mostly problems in biojava parsing. Many of them would go with biojava 5, if we can't patch the 4.2 branch for this, the problems would go with an upgrade to biojava 5.

**Comment by lafita** [comment]
It would be good to raise this issue in biojava, because I think that the condition of an empty chain (no representative atoms) should be checked before trying to calculate the moments of inertia, probably when the subunits are passed into the symmetry detector (since an empty subunit is also an illegal argument).

I was getting this issue sometimes in CE-Symm as well, and it was difficult to debug and interpret the error because of that - it appears too late.

**Comment by josemduarte** [comment]
I've fixed it now by using all atoms if no representative atoms can be found. In biojava I've added an earlier check for empty atom arrays that should help, see https://github.com/biojava/biojava/commit/0f322ee84f9ec3e2e86d710fe91ad47016c15032
