### ISSUE TITLE
Interface calculation fails for some entries

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#186]
E.g. 2v52 and 2y27. The stack trace:

```
Loading PDB data: 2y27
09:21:18 [main] WARN  org.biojava.nbio.structure.io.mmcif.SimpleMMcifConsumer - Could not find a compound for entity_id 8, for chain id D, creating a new compound.
Calculating possible interfaces...
09:21:18 [main] ERROR org.biojava.nbio.structure.contact.StructureInterfaceList - Error! Empty list of atoms
09:21:18 [main] ERROR eppic.Main - Unexpected error. Stack trace:
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.biojava.nbio.structure.contact.BoundingBox.<init>(BoundingBox.java:79)
	at org.biojava.nbio.structure.xtal.UnitCellBoundingBox.setBb(UnitCellBoundingBox.java:76)
	at org.biojava.nbio.structure.xtal.UnitCellBoundingBox.setBbs(UnitCellBoundingBox.java:64)
	at org.biojava.nbio.structure.xtal.CrystalBuilder.calcInterfacesCrystal(CrystalBuilder.java:239)
	at org.biojava.nbio.structure.xtal.CrystalBuilder.getUniqueInterfaces(CrystalBuilder.java:203)
	at eppic.Main.doFindInterfaces(Main.java:271)
	at eppic.Main.run(Main.java:944)
	at eppic.Main.run(Main.java:913)
	at eppic.Main.main(Main.java:887)
```
This is an issue in biojava parsing. Probably easiest way to solve it is upgrading to biojava 5 when it's out.

**Comment by josemduarte** [comment]
These 2 work ok now, I guess because of recent remediation at PDB? I'll close, please reopen if issue found for other examples.
