### ISSUE TITLE
CLI crashes on 5xnl doing graph contraction

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#196]
The stack trace:
```
java.lang.IllegalArgumentException: no such vertex in graph: m_0
        at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:132)
        at org.jgrapht.graph.AbstractBaseGraph.edgesOf(AbstractBaseGraph.java:338)
        at eppic.assembly.GraphContractor.contractInterfaceCluster(GraphContractor.java:123)
        at eppic.assembly.GraphContractor.contract(GraphContractor.java:241)
        at eppic.assembly.LatticeGraph.contractGraph(LatticeGraph.java:466)
        at eppic.assembly.CrystalAssemblies.init(CrystalAssemblies.java:124)
        at eppic.assembly.CrystalAssemblies.<init>(CrystalAssemblies.java:94)
        at eppic.Main.doFindAssemblies(Main.java:366)
        at eppic.Main.run(Main.java:948)
        at eppic.Main.run(Main.java:913)
        at eppic.Main.main(Main.java:887)

```
Also happens for 5xnm

**Comment by josemduarte** [comment]
A simpler example where this also happens: 1kbu

There's another 124 cases across the PDB right now
