### ISSUE TITLE
CLI crash on 3spu

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#206]
In interface calculation. Log:
```
2018-01-29 07:57:34 ERROR - Error! Empty list of atoms
2018-01-29 07:57:34 ERROR - Unexpected error. Stack trace:
java.lang.ArrayIndexOutOfBoundsException: 0
        at org.biojava.nbio.structure.contact.BoundingBox.<init>(BoundingBox.java:79)
        at org.biojava.nbio.structure.xtal.UnitCellBoundingBox.setBb(UnitCellBoundingBox.java:76)
        at org.biojava.nbio.structure.xtal.UnitCellBoundingBox.setBbs(UnitCellBoundingBox.java:64)
        at org.biojava.nbio.structure.xtal.CrystalBuilder.calcInterfacesCrystal(CrystalBuilder.java:239)
        at org.biojava.nbio.structure.xtal.CrystalBuilder.getUniqueInterfaces(CrystalBuilder.java:203)
        at eppic.Main.doFindInterfaces(Main.java:271)
        at eppic.Main.run(Main.java:952)
        at eppic.Main.run(Main.java:921)
        at eppic.Main.main(Main.java:895)
```
Similar issue in 1uon

**Comment by josemduarte** [comment]
Possibly same issue as #186

**Comment by josemduarte** [comment]
The issue here is that all waters are assigned to a separate author chain id "W". When getting the atom array out of it, 0 atoms are returned. Solution should be skipping pure water chains.

**Comment by josemduarte** [comment]
The issue is in biojava 4.x. The `CrystalBuilder` constructor should handle how to initialise the `numChainsAu` and skip pure water chains. In biojava 5 this is solved, since poly and non-poly chains are clearly separated. This issue would go away when upgrading to biojava 5.

**Comment by josemduarte** [comment]
Same issue as #212

**Comment by josemduarte** [comment]
Fixed by move to biojava 5, see biojava5 branch
