### ISSUE TITLE
CLI crash on 5lwg

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#207]
Log:
```
2018-01-29 07:02:47 ERROR - Unexpected error. Stack trace:
java.lang.IllegalArgumentException: Input vectors are parallel
        at eppic.commons.util.GeomTools.matrixFromPlane(GeomTools.java:116)
        at eppic.commons.util.GeomTools.matrixFromPlane(GeomTools.java:149)
        at eppic.assembly.ParametricCircularArc.<init>(ParametricCircularArc.java:78)
        at eppic.assembly.ParametricCircularArc.<init>(ParametricCircularArc.java:90)
        at eppic.assembly.LatticeGraph3D.positionEdges(LatticeGraph3D.java:225)
        at eppic.assembly.LatticeGraph3D.<init>(LatticeGraph3D.java:136)
        at eppic.Main.doWriteAssemblyDiagrams(Main.java:572)
        at eppic.Main.run(Main.java:987)
        at eppic.Main.run(Main.java:921)
        at eppic.Main.main(Main.java:895)
```

**Comment by josemduarte** [comment]
The entry has lots of clashes, so the issue can be a consequence of that. We are not stopping in too many clashes case since 3.0.4
