### ISSUE TITLE
Concurrent Modification Exception in graph contraction

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#208]
3pml crashes in doing graph contraction. Log:

```
2018-01-29 06:09:19 ERROR - Unexpected error. Stack trace:
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:907)
        at java.util.ArrayList$Itr.next(ArrayList.java:857)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
        at eppic.assembly.GraphContractor.contractInterfaceCluster(GraphContractor.java:129)
        at eppic.assembly.GraphContractor.contract(GraphContractor.java:252)
        at eppic.assembly.LatticeGraph.contractGraph(LatticeGraph.java:466)
        at eppic.assembly.CrystalAssemblies.init(CrystalAssemblies.java:125)
        at eppic.assembly.CrystalAssemblies.<init>(CrystalAssemblies.java:95)
        at eppic.Main.doFindAssemblies(Main.java:374)
        at eppic.Main.run(Main.java:956)
        at eppic.Main.run(Main.java:921)
        at eppic.Main.main(Main.java:895)
```

**Comment by josemduarte** [comment]
Other examples: 2esv, 5t58, 2hhh
